//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnotationProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TextAnnotationEntities : DbContext
    {
        public TextAnnotationEntities()
            : base("name=TextAnnotationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Annotation> Annotations { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<TextTag> TextTags { get; set; }
        public DbSet<Text> Texts { get; set; }
        public DbSet<UserLike> UserLikes { get; set; }
    }
}
