//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnotationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Annotation
    {
        public int ID { get; set; }
        public int BaseTextID { get; set; }
        public int AnnotationTextID { get; set; }
        public string TextAnchor { get; set; }
    
        public virtual Text Text { get; set; }
        public virtual Text Text1 { get; set; }
    }
}
