//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnotationProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Text
    {
        public Text()
        {
            this.Annotations = new HashSet<Annotation>();
            this.Annotations1 = new HashSet<Annotation>();
            this.TextTags = new HashSet<TextTag>();
        }
    
        public int ID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string Author { get; set; }
        public bool IsBaseText { get; set; }
        public string Title { get; set; }
        public bool IsArchived { get; set; }
        public int UserID { get; set; }
        public int AnnotationCount { get; set; }
        public Nullable<int> NextTextID { get; set; }
        public Nullable<int> PrevTextID { get; set; }
        public int FavoritedCount { get; set; }
    
        public virtual ICollection<Annotation> Annotations { get; set; }
        public virtual ICollection<Annotation> Annotations1 { get; set; }
        public virtual ICollection<TextTag> TextTags { get; set; }
    }
}
